
CREATE DATABASE IF NOT EXISTS DSPRODUCTCATALOG2;

CREATE DATABASE IF NOT EXISTS DSPRODUCTORDERING;

CREATE DATABASE IF NOT EXISTS DSPRODUCTINVENTORY;

CREATE DATABASE IF NOT EXISTS DSPARTYMANAGEMENT;

CREATE DATABASE IF NOT EXISTS DSBILLINGMANAGEMENT;

CREATE DATABASE IF NOT EXISTS DSCUSTOMER;

CREATE DATABASE IF NOT EXISTS DSUSAGEMANAGEMENT;

CREATE DATABASE IF NOT EXISTS RSS;
