db:
    image: mysql:latest
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw
        - MYSQL_DATABASE=RSS

rss:
    image: rss
    ports:
        - "9999:8080"
        - "4848:4848"
        - "8181:8181"
    links:
        - db
    environment:
        - RSS_CLIENT_ID=POTORRO
        - RSS_SECRET=PLATANO
        - RSS_URL=http://db:9999