rss_db:
    image: mysql:latest
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw
        - MYSQL_DATABASE=RSS

rss:
    image: rss
    ports:
        - "9999:8080"
    links:
        - rss_db
    environment:
        - RSS_CLIENT_ID=POTORRO
        - RSS_SECRET=PLATANO
        - RSS_URL=FUNCIONAPUTA
